export const NOTIFICATION_CONSTANTS = {
    ADD:'add',
    EDIT:'edit',
    DELETE:'delete',
    EDIT_CONFIRM_TYPE:'Edit_Confirm',
    ADD_CONFIRM_TYPE:'Add_Confirm',
    DELETE_CONFIRM_TYPE:'Delete_Confirm',
    ERROR_NOTIFICATION_TYPE:'Error Notification',
    REMINDER_TYPE:'Reminder',
    WARNING_TYPE:'Warning',
    INFORMATION_TYPE:'Information',
    CANCEL_TYPE:'Cancel',
    CANCELED_STATUS:'Canceled', 
    FAILED_STATUS:'Failed',
    COMPLETED_STATUS:'Completed',
    PENDING_STATUS:'Pending',
    INPROGRESS_STATUS:'In Progress',
    SCHELUDED_STATUS:'Scheduled',
    ACTION_BUTTON:'Confirm',
    GLOBAL_DELETE_TITLE:'Delete Confirmation',
    GLOBAL_DELETE_CONTENT: 'Are you sure you want to delete this (item)? This action is irreversible and will remove all related information, including plants and records. Please confirm before proceeding.',
    GLOBAL_DELETE_WARN:'',
    GLOBAL_EDIT_TITLE:'Save the changes',
    GLOBAL_EDIT_CONTENT: 'Are you sure you want to save the changes? ',
    GLOBAL_EDIT_WARN:'Once this action is performed, it cannot be undone.',
    ADD_CLIENT_TITLE: 'Add new client',
    ADD_CLIENT_CONTENT: 'Please review the data carefully before saving.',
    ADD_CLIENT_WARN: 'Fields like the start date and ID cannot be edited once saved.',
    ADD_CLIENT_COMPLETE_TITLE:'Client added',
    ADD_CLIENT_COMPLETE_CONTENT:'A new client has been successfully added.',
    EDIT_CLIENT_COMPLETE_TITLE:'Changes saved',
    EDIT_CLIENT_COMPLETE_CONTENT:'Your data has been successfully saved.',
    CANCEL_ADD_CLIENT_TITLE: 'Cancel new client',
    CANCEL_ADD_CLIENT_CONTENT: 'Are you sure you want to cancel adding this company? All entered information will be lost, and no changes will be saved',
  };
  