name: Build and deploy Node.js app to Azure Web App Dev - er-portal

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: er-portal   
  NODE_VERSION: '20.x'              

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build
        run: |
          npm install --force --verbose
          npm run build -- --configuration=development

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip dist/er-portal/browser

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

      - name: List dist folder
        run: ls -R ./dist/er-portal

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
          path: .

      - name: Unzip artifact
        run: unzip release.zip -d release

      - name: Clean deployment directory
        run: |
          rm -rf /home/site/wwwroot/*

      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'dev'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEVELOP }}
          package: 'release/dist/er-portal/browser/browser'
