name: Build and deploy Node.js app to Azure Web App - er-portal

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: er-portal   
  AZURE_WEBAPP_PACKAGE_PATH: './dist/er-portal/browser/en-US'    
  NODE_VERSION: '20.x'              

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build
        run: |
          npm install
          npm run build --if-present

      - name: List build directory
        run: ls -R ./dist/er-portal/browser

      - name: Zip artifact for deployment
        run: zip -r release.zip ./dist/er-portal/browser

      - name: List contents of the ZIP file
        run: unzip -l release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: List contents of the downloaded artifact
        run: unzip -l release.zip

      - name: Unzip artifact for deployment
        run: unzip release.zip -d ./dist/er-portal/browser

      - name: List directory contents after unzip
        run: ls -R ./dist/er-portal/browser

      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './dist/er-portal/browser/en-US'

      run: echo "Hello ${{ inputs.name }}"
